dataset = "construct"
seed = 88888888
epochs = 1000
batch_size=16
device = "cuda"
model_chosen = 'RF'
confactor = 0.1

[optimizer]

    opt = 'AdamW'
    lr = 0.0025
#    lr = 0.005
    weight_decay=1e-05
    amsgrad='True'
    opt_scheduler='none'

[model]

    device = "cuda"
    confactor = 0.1

    [model.feature_extractor]
    type = 'linear'
    n_features = 2
    dropout_rate = 0
    hidden_neurons = [4, 8]
    batch_norm = 'True'
    hidden_activation = 'relu'

    [model.autoencoder]
    type = 'linear'
    n_features = 2
    dropout_rate = 0.1
    hidden_neurons = [2, 4]
    batch_norm = 'True'
    hidden_activation = 'relu'

    [model.puIF]
    type = 'linear'
    n_features = 2
    dropout_rate = 0.1
    hidden_neurons = [2, 4, 1]
    batch_norm = 'True'
    hidden_activation = 'relu'

    [model.attention]
    L=8  # Attention model input nodes
    D=4  # Attention model intermediate nodes
    K=1  # Attention model output nodes

