output="result/pum6a/293T_4"

[dataload]
    signal="result/caNano/HEK293T_4/wt.feature.tsv"
    motif=  ["AAACA", "AAACT", "AGACC", "GAACA", "GAACT", "GGACC", "AAACC", "AGACA", "AGACT", "GAACC", "GGACA", "GGACT"]
#    motif=  ["AAACA"]
    min_read=3
    inference=true

[model]
    model_path = 'result/293T_model/KNUME_231223161935_88888888_ran_model.pt'
    device = 'cuda'
