seed = 8

[dataload]

    dataset = "MUSK1"
    num_bag = 500
    mean_nbag_length = 10
    var_nbag_length = 2
    mean_abag_length = 4
    var_abag_length = 1
    confactor = 0.3
    target = 1
    seed = 8

[model]

    model_chosen = 'puIF' # pum6a, puma, iAE, puIF, RF, PU-SKC, puMIL, LSDD.toml, DSDD
    device = 'cuda'

    [model.feature_extractor]
    type = 'linear'
    n_features = 166
    dropout_rate = 0
    hidden_neurons = [4, 2] # [4, 2]
    batch_norm = true
    hidden_activation = 'relu'

[trainer]

    trainer_chosen='puIF_Trainer' # adanTrainer, puIF_Trainer, RF_Trainer, Trainer
    device = 'cuda'
    n_splits = 5    # 5-fold-cross-validataion
    save_dir = 'result/'
    seed = 8

    epochs = 1000 # 100, 1000
    batch_size = 16 # 16/16*14=224
    n_pos = 6  # 500*0.3*0.8**0.10=6
    freq = 5  # 5% freqency
    early_stopping = 3

    [trainer.optimizer]

    opt = 'AdamW'
    lr = 0.0025 # 0.0001
    weight_decay=1e-05
    amsgrad=true
    opt_scheduler='none'