seed = 8

[dataload]

    dataset = "MUSK1"
    num_bag = 500
    mean_nbag_length = 10
    var_nbag_length = 2
    confactor = 0.3
    target = 1
    seed = 8

[model]

    model_chosen = 'pum6a' # pum6a, puma, iAE, puIF, RF, PU-SKC, puMIL, LSDD.toml, DSDD
    device = 'cuda'

    [model.feature_extractor]
    type = 'linear'
    n_features = 166
    dropout_rate = 0
    hidden_neurons = [64, 32]
    batch_norm = true
    hidden_activation = 'relu'

    [model.classifier]
    input = 2

    [model.attention]
    L=32  # Attention model_factory input nodes
    D=16  # Attention model_factory intermediate nodes
    K=1  # Attention model_factory output nodes

[trainer]

    trainer_chosen='adanTrainer' # adanTrainer, puIF_Trainer, RF_Trainer, Trainer
    device = 'cuda'
    n_splits = 5    # 5-fold-cross-validataion
    save_dir = 'result/MUSK1/pum6a/10'
    seed = 8

    epochs = 300 # 100, 1000
    batch_size = 16
    freq = 10  # 10% freqency
    n_pos = 4  # 47*0.8*0.1 = 4
    early_stopping = 3

    [trainer.optimizer]

    opt = 'AdamW'
    lr = 0.001
    weight_decay=1e-05
    amsgrad=true
    opt_scheduler='none'