seed = 88888888

[dataload]

    dataset = "Thyroid"
    num_bag = 500
    mean_nbag_length = 10
    var_nbag_length = 2
    mean_abag_length = 4
    var_abag_length = 1
    confactor = 0.3
    target = 1
    seed = 8888888


[model]

    model_chosen = 'PU-SKC' # pum6a, puma, iAE, puIF, RF, PU-SKC, puMIL, LSDD, DSDD


[trainer]

    trainer_chosen='Trainer' # adanTrainer, puIF_Trainer, RF_Trainer, Trainer
    model_chosen='PU-SKC' # PU-SKC, puMIL, LSDD, DSDD
    device = 'cuda'
    n_splits = 5    # 5-fold-cross-validataion
    save_dir = 'result/Annthyroid'
    seed = 8888888

    epochs = 1000 # 100, 1000
    batch_size = 224 # 16/16*14=224
    n_pos = 40  # 500*0.3*0.8**0.10=6
    freq = 5  # 5% freqency
    early_stopping = 3

    [trainer.puskc]
    aucplot=false
    np=20
    nu=180
    prior=0.2
    verbose=false
    loss='double_hinge'