seed = 8

[dataload]

    dataset = "MNIST"
    num_bag = 500
    mean_nbag_length = 10
    var_nbag_length = 2
    confactor = 0.3
    target = 9
    seed = 8


[model]

    model_chosen = 'puma' # pum6a, puma, iAE, puIF, RF, PU-SKC, puMIL, LSDD.toml, DSDD
    device = 'cuda'

    [model.autoencoder]
    type = 'linear'
    n_features = 784
    dropout_rate = 0
    hidden_neurons = [512, 256, 128]
    batch_norm = false
    hidden_activation = 'relu'


[trainer]

    trainer_chosen='adanTrainer' # adanTrainer, puIF_Trainer, RF_Trainer, Trainer
    device = 'cuda'
    n_splits = 5    # 5-fold-cross-validataion
    save_dir = 'result/MNIST/puma/10'
    seed = 8

    epochs = 300 # 100, 1000
    batch_size = 16
    freq = 0.1  # 50% freqency
    early_stopping = 3
    verbose = false

    [trainer.optimizer]

    opt = 'AdamW'
    lr = 0.0025 # 0.0001
    weight_decay=1e-05
    amsgrad=true
    opt_scheduler='none'