seed = 88888

[dataload]

    dataset = "Wilt"
    num_bag = 500
    mean_nbag_length = 10
    var_nbag_length = 2
    confactor = 0.3
    target = 1
    seed = 88888


[model]

    model_chosen = 'RF'

[trainer]

    trainer_chosen='RF_Trainer' # adanTrainer, puIF_Trainer, RF_Trainer, Trainer
    model_chosen='RF'
    n_splits = 5    # 5-fold-cross-validataion
    save_dir = 'result/Anomaly_detection/Wilt/RF/10'
    seed = 88888
    freq = 0.1
