seed = 8

[dataload]

    dataset = "PageBlock"
    num_bag = 500
    mean_nbag_length = 10
    var_nbag_length = 2
    confactor = 0.3
    target = 1
    seed = 8


[model]

    model_chosen = 'iAE' # pum6a, puma, iAE, puIF, RF, PU-SKC, puMIL, LSDD.toml, DSDD
    device = 'cuda'

    [model.autoencoder]
    type = 'linear'
    n_features = 10
    dropout_rate = 0
    hidden_neurons =  [8, 4]
    batch_norm = false
    hidden_activation = 'relu'


[trainer]

    trainer_chosen='adanTrainer' # adanTrainer, puIF_Trainer, RF_Trainer, Trainer
    device = 'cuda'
    n_splits = 5    # 5-fold-cross-validataion
    save_dir = 'result/MUSK1/iAE/10'
    seed = 8

    epochs = 100 # 100, 1000
    batch_size = 16 # 16/16*14=224
    n_pos = 40  # 47*0.8**=6
    freq = 10  # 5% freqency
    early_stopping = 3

    [trainer.optimizer]

    opt = 'AdamW'
    lr = 0.0025 # 0.0001
    weight_decay=1e-05
    amsgrad=true
    opt_scheduler='none'