seed = 88888888

[dataload]

    dataset = "Annthyroid"
    num_bag = 500
    mean_nbag_length = 10
    var_nbag_length = 2
    mean_abag_length = 4
    var_abag_length = 1
    confactor = 0.3
    target = 1
    seed = 8888888


[model]

    model_chosen = 'pum6a' # pum6a, puma, iAE, puIF, RF, PU-SKC, puMIL, LSDD, DSDD
    device = 'cuda'
#    type = 'conv'
#    kernal_size = 5
#    pool_kernal_size = 2
#    pool_stride = 2
#    hidden_neurons = [20, 50]
#    hidden_activation = 'relu'
#    linear_input = 800 # 50 * 4 * 4
    [model.randomforest]
     n_estimators = [10, 20, 30, 40, 50, 100]
     max_features = ['auto', 'sqrt']
     max_depth = [2, 4, 6, 8, 10, 20]
     min_samples_split = [1, 2, 4, 6, 8]
     min_samples_leaf = [1, 2, 4, 6, 8]

    [model.isoForest]
    contamination=0.25 # mean_abag_length/mean_nbag_length

    [model.feature_extractor]
    type = 'linear'
    n_features = 6
    dropout_rate = 0
    hidden_neurons = [4, 2] # [4, 2]
    batch_norm = 'True'
    hidden_activation = 'relu'

    [model.classifier]
    input = 2
#    [model.attention]
#    L=500  # Attention model_factory input nodes
#    D=128  # Attention model_factory intermediate nodes
#    K=1    # Attention model_factory output nodes

    [model.attention]
    L=2  # Attention model_factory input nodes
    D=1  # Attention model_factory intermediate nodes
    K=1    # Attention model_factory output nodes


    [model.autoencoder]
    type = 'linear'
    n_features = 6
    dropout_rate = 0.1
    hidden_neurons = [4, 2]
    batch_norm = 'True'
    hidden_activation = 'relu'

[trainer]

    trainer_chosen='adanTrainer' # adanTrainer, puIF_Trainer, RF_Trainer
    device = 'cuda'
    n_splits = 5    # 5-fold-cross-validataion
    save_dir = 'result/Annthyroid'
    seed = 8888888

    epochs = 1000 # 100, 1000
    batch_size = 224 # 16/16*14=224
    n_pos = 20  # 500*0.8*0.05=20
    freq = 5  # 5% freqency
    early_stopping = 3

    [trainer.optimizer]

    opt = 'AdamW'
    lr = 0.0025 # 0.0001
    weight_decay=1e-05
    amsgrad='True'
    opt_scheduler='none'

